import asyncio
import json
import os
import re
from openai import AsyncOpenAI  
from slime.utils.types import Sample  

# remote_reward_model.py 顶部
_client = None

def get_client(api_key, base_url):
    global _client
    if _client is None:
        _client = AsyncOpenAI(
            api_key=api_key, 
            base_url=base_url,
            max_retries=3,
            timeout=60
        )
    return _client


MATH_JUDGE_TEMPLATE = '''I will now give you a question, the final portion of an answer generated by an AI assistant, and the correct answer to the question. 

Please note: The [AI Assistant Answer] provided below is only the LAST PART (the tail) of the original full response. You should focus on the final steps and the concluding result contained within this snippet to determine whether it is consistent with the ground truth.

Important: You do not need to compute or solve the problem yourself. Just judge whether the AI Assistant's conclusion matches the provided Ground Truth; use the question text only as context if needed.

- ---------------- [Question Start] -----------------

{prompt}

- ---------------- [Question End] -----------------
- ---------------- [AI Assistant Answer (Final Part)] -----------------

{response}

- ---------------- [AI Assistant Answer End] -----------------
- ---------------- [Ground Truth Start] -----------------

{label}

- ---------------- [Ground Truth End] -----------------

Please structure your response in three lines:
1. Line 1: Analyze the AI assistant's final reasoning/conclusion in the provided snippet.
2. Line 2: Confirm what the correct answer is.
3. Line 3: Compare the two and judge whether the AI assistant's answer is consistent with the correct answer. Provide your conclusion, consistent or inconsistent, in English within <result></result> tags, i.e., <result>consistent</result> or <result>inconsistent</result>.

Do not output anything other than the above.

Output:
'''.strip()


JUDGE_PROMPTS = {  
    "math": MATH_JUDGE_TEMPLATE,
    "general": "请评估以下问答的质量。问题：{prompt}\n回答：{response}\n参考答案：{label}\n请返回 0-1 之间的分数，评估回答的准确性和相关性。",  
    "code": "请评估以下代码问题的解答。问题：{prompt}\n代码：{response}\n参考答案：{label}\n请返回 0-1 之间的分数，重点关注代码正确性和效率。",  
    "custom": "{custom_prompt}"  # 支持完全自定义的 prompt  
}  


def compute_reward_result_tag(judge_response):
    """从 judge 模型响应中提取判定结果标签。
    
    返回与规则计算一致的奖励值：
    - 1.0: 答案正确（consistent）
    - -1.0: 答案错误（inconsistent）或解析失败
    
    Args:
        judge_response: judge模型的响应文本
        
    Returns:
        float: 奖励分数，1.0表示正确，-1.0表示错误
    """
    if not judge_response:
        return -1.0
    
    result_match = re.findall(r"<result>(.*?)</result>", judge_response)
    if result_match and len(result_match) >= 1:
        try:
            judge_item_res = result_match[-1].strip().lower() == "consistent"
            # 返回浮点数，与规则计算一致：1.0表示正确，-1.0表示错误
            return 1.0 if judge_item_res else -1.0
        except Exception as e:
            return -1.0
    else:
        # 如果没有找到result标签，认为judge失败，返回-1.0（错误）
        return -1.0


async def remote_reward_function(args, sample: Sample, **kwargs) -> float:  
    """  
    自定义 reward function，调用 OpenAI 兼容的 API  
      
    Args:  
        args: slime 训练参数  
        sample: 包含 prompt、response、label 的样本  
        **kwargs: 其他参数  
      
    Returns:  
        float: reward 分数  
    """
    # 1. 获取 API 配置（优先级：命令行参数 > 环境变量 > 默认值）  
    api_key = getattr(args, 'rm_api_key', None) or os.getenv('RM_API_KEY', 'EMPTY')  
    base_url = getattr(args, 'rm_base_url', None) or os.getenv('RM_BASE_URL')  
    model_name = getattr(args, 'rm_model_name', None) or os.getenv('RM_MODEL_NAME', 'Qwen3-30B-A3B')  
      
    if not base_url:  
        raise ValueError("base_url is required. Set --rm-base-url or RM_BASE_URL environment variable")  
      
    # 2. 获取数据类型和 prompt 配置  
    metadata = sample.metadata if isinstance(sample.metadata, dict) else {}  
    breakpoint()
    # 从 metadata 中获取数据类型，默认为 "math"  
    data_type = metadata.get('data_type', 'math')  
      
    # 获取 judge prompt，支持多种配置方式  
    if 'judge_prompt' in metadata:
        # 优先使用 metadata 中的自定义 prompt  
        judge_template = metadata['judge_prompt']  
        prompt_type = 'custom'  
    elif data_type in JUDGE_PROMPTS:  
        # 使用预定义的 prompt 模板  
        judge_template = JUDGE_PROMPTS[data_type]
        prompt_type = data_type
    else:  
        # 回退到通用 prompt  
        judge_template = JUDGE_PROMPTS['general']  
        prompt_type = 'general'  
      
    # 3. 构造评估 prompt
    raw_response = sample.response
    response_text = str(raw_response)[-1000:]

    judge_prompt = judge_template.format(  
        prompt=sample.prompt[-1]["content"] if isinstance(sample.prompt, list) else sample.prompt,
        response=response_text,  
        label=sample.label or "无参考答案",  
        custom_prompt=metadata.get('judge_prompt', '')  
    )
    #print("📝 评估 Prompt:", {"judge_prompt": judge_prompt})

    # 初始化 OpenAI 客户端  
    client = get_client(api_key, base_url)

    try:  
        response = await client.chat.completions.create(  
            model=model_name,  
            messages=[
                {"role": "user", "content": judge_prompt}  
            ],
            temperature=0.0,  
            max_tokens=2000,
            extra_body={"chat_template_kwargs": {"thinking": False}}            ,
        )  
        
        # 5. 解析和返回分数
        score_text = response.choices[0].message.content.strip()  
        # print("📝 评估结果: ", {'score_text': score_text})
        score = compute_reward_result_tag(score_text)
        breakpoint()
        return {"reward": score, "score": score, "acc": 0 if score <= 0 else 1}
            
    except Exception as e:  
        print("📝 评估 Prompt:", {"judge_prompt": judge_prompt})
        print(f"Reward model API 调用失败: {e}")  
        return {"reward": -1.0, "score": -1.0, "acc": 0}